name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v main.go
      - name: Unit tests
        run: go test tests/file_level_test.go -json > TestResults-units.json
      - name: Fuzzy integration testing
        run: go test tests/fuzzy_integration_test.go > TestResults-fuzzy.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: TestResults-{units,fuzzy}.json