name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.x'
      - name: Build
        run: go mod tidy && go build -v apps/sync/sync.go
      - name: Unit tests
        run: go test tests/file_level_test.go
      - name: Fuzzy integration testing
        run: go test tests/fuzzy_integration_test.go